services:
  app:
    image: nestjs_app_prod:1.0.0
    build:
      args:
        MYSQL_HOST: "db"
        MYSQL_PORT: 3306
        MYSQL_DATABASE: 'nestjs_app_prod'
        MYSQL_USERNAME: 'root'
        MYSQL_PASSWORD: '12345678'
        MYSQL_ROOT_PASSWORD: '12345678'
        NODE_ENV: "production"
      context: .
      dockerfile: Dockerfile.prod
    environment:
      MYSQL_HOST: "db"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'nestjs_app_prod'
      MYSQL_USERNAME: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.5.0
    container_name: mysql_prod
    environment:
      MYSQL_DATABASE: 'nestjs_app_prod'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  mysql_data_prod:
